# Generated by Django 3.2.8 on 2023-09-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayFieldOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberOfPorts', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('goipType', models.IntegerField(choices=[(0, 'GSM goip'), (1, 'Sim Banks')])),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='GoIPPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('smsServerLine', models.CharField(blank=True, max_length=255, null=True)),
                ('simCardNumber', models.CharField(blank=True, max_length=20)),
                ('goip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageBox', to='backend.goip')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paymentType', models.CharField(choices=[('onetime', 'یکبار'), ('month', 'ماهانه'), ('year', 'سالانه'), ('week', 'هفتگی')], max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('stripeId', models.CharField(blank=True, max_length=200)),
                ('activationPlanPrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.planprice')),
            ],
        ),
        migrations.CreateModel(
            name='SMSServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoIPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberSimCalls', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='VoIP3CXAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extention', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='backend.voipserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voipAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeId', models.CharField(max_length=300)),
                ('nationalId', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stripeId', models.CharField(max_length=200)),
                ('cardNumber', models.CharField(max_length=20)),
                ('expiryDate', models.CharField(max_length=7)),
                ('nameOnCard', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stripeId', models.CharField(blank=True, max_length=200)),
                ('pricePlanSubscriptionStripeId', models.CharField(blank=True, max_length=200)),
                ('isActive', models.BooleanField(default=False)),
                ('currentPeriodEnd', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.IntegerField(blank=True, choices=[(0, 'آسیاتک'), (1, 'همراه اول'), (2, 'ایرانسل'), (3, 'پیشگامان')], null=True)),
                ('location', models.IntegerField(blank=True, choices=[(0, 'ایران'), (1, 'کانادا')], null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20)),
                ('userData', models.JSONField()),
                ('goipPort', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='backend.goipport')),
                ('planPrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='backend.planprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('userCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='backend.usercard')),
                ('voip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='backend.voip3cxaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('stripeId', models.CharField(blank=True, max_length=200)),
                ('productModels', models.ManyToManyField(blank=True, null=True, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='planprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backend.product'),
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('contactInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageBox', to='backend.contact')),
                ('goipPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageBox', to='backend.goipport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('messageType', models.IntegerField(choices=[(0, 'send'), (1, 'receive')])),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('messageBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.messagebox')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.IntegerField(choices=[(0, 'کارت'), (1, 'نقدی')])),
                ('chargeType', models.IntegerField(choices=[(0, 'پرداخت'), (1, 'بازگشت')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='backend.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goipport',
            name='smsServer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageBox', to='backend.smsserver'),
        ),
        migrations.AddField(
            model_name='goipport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisplayField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputType', models.CharField(max_length=100)),
                ('inputId', models.CharField(max_length=100)),
                ('inputName', models.CharField(max_length=100)),
                ('inputPlaceholder', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('required', models.BooleanField()),
                ('options', models.ManyToManyField(blank=True, to='backend.DisplayFieldOptions')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayField', to='backend.product')),
            ],
            options={
                'verbose_name': 'DisplayField',
                'verbose_name_plural': 'DisplayField',
                'unique_together': {('product', 'order')},
            },
        ),
    ]
