# Generated by Django 3.2.8 on 2023-09-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230909_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='messagebox',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
